// Area number → issuing state mapping (pre-2011 SSA issuance patterns)
export function getStateFromArea(area) {
  const areaNum = parseInt(area);
  if (isNaN(areaNum)) return 'Unknown';
  if (areaNum >= 1 && areaNum <= 3) return 'New Hampshire';
  if (areaNum >= 4 && areaNum <= 7) return 'Maine';
  if (areaNum >= 8 && areaNum <= 9) return 'Vermont';
  if (areaNum >= 10 && areaNum <= 34) return 'Massachusetts';
  if (areaNum >= 35 && areaNum <= 39) return 'Rhode Island';
  if (areaNum >= 40 && areaNum <= 49) return 'Connecticut';
  if (areaNum >= 50 && areaNum <= 134) return 'New York';
  if (areaNum >= 135 && areaNum <= 158) return 'New Jersey';
  if (areaNum >= 159 && areaNum <= 211) return 'Pennsylvania';
  if (areaNum >= 212 && areaNum <= 220) return 'Maryland';
  if (areaNum >= 221 && areaNum <= 222) return 'Delaware';
  if (areaNum >= 223 && areaNum <= 231) return 'Virginia';
  if (areaNum >= 232 && areaNum <= 236) return 'West Virginia';
  if (areaNum >= 237 && areaNum <= 246) return 'North Carolina';
  if (areaNum >= 247 && areaNum <= 251) return 'South Carolina';
  if (areaNum >= 252 && areaNum <= 260) return 'Georgia';
  if (areaNum >= 261 && areaNum <= 267) return 'Florida';
  if (areaNum >= 268 && areaNum <= 302) return 'Ohio';
  if (areaNum >= 303 && areaNum <= 317) return 'Indiana';
  if (areaNum >= 318 && areaNum <= 361) return 'Illinois';
  if (areaNum >= 362 && areaNum <= 386) return 'Michigan';
  if (areaNum >= 387 && areaNum <= 399) return 'Wisconsin';
  if (areaNum >= 400 && areaNum <= 407) return 'Kentucky';
  if (areaNum >= 408 && areaNum <= 415) return 'Tennessee';
  if (areaNum >= 416 && areaNum <= 424) return 'Alabama';
  if (areaNum >= 425 && areaNum <= 428) return 'Mississippi';
  if (areaNum >= 429 && areaNum <= 432) return 'Arkansas';
  if (areaNum >= 433 && areaNum <= 439) return 'Louisiana';
  if (areaNum >= 440 && areaNum <= 448) return 'Oklahoma';
  if (areaNum >= 449 && areaNum <= 467) return 'Texas';
  if (areaNum >= 468 && areaNum <= 477) return 'Minnesota';
  if (areaNum >= 478 && areaNum <= 485) return 'Iowa';
  if (areaNum >= 486 && areaNum <= 500) return 'Missouri';
  if (areaNum >= 501 && areaNum <= 502) return 'North Dakota';
  if (areaNum >= 503 && areaNum <= 504) return 'South Dakota';
  if (areaNum >= 505 && areaNum <= 508) return 'Nebraska';
  if (areaNum >= 509 && areaNum <= 515) return 'Kansas';
  if (areaNum >= 516 && areaNum <= 517) return 'Montana';
  if (areaNum >= 518 && areaNum <= 519) return 'Idaho';
  if (areaNum === 520) return 'Wyoming';
  if (areaNum >= 521 && areaNum <= 524) return 'Colorado';
  if (areaNum === 525) return 'New Mexico';
  if (areaNum >= 526 && areaNum <= 527) return 'Arizona';
  if (areaNum >= 528 && areaNum <= 529) return 'Utah';
  if (areaNum === 530) return 'Nevada';
  if (areaNum >= 531 && areaNum <= 539) return 'Washington';
  if (areaNum >= 540 && areaNum <= 544) return 'Oregon';
  if (areaNum >= 545 && areaNum <= 573) return 'California';
  if (areaNum === 574) return 'Alaska';
  if (areaNum >= 575 && areaNum <= 576) return 'Hawaii';
  if (areaNum >= 577 && areaNum <= 579) return 'District of Columbia';
  if (areaNum === 580) return 'Virgin Islands';
  if (areaNum >= 581 && areaNum <= 584) return 'Puerto Rico';
  if (areaNum >= 587 && areaNum <= 899) return 'Randomized (Post-2011)';
  return 'Unknown';
}